sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.3
jobs:
  include:
    - if: branch = master
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- rm -rf dependencies/jekyll/.git/
- rm -rf dependencies/jekyll/*.md
- mv dependencies/jekyll/* .
- rm -rf dependencies
- mv sidebar.yml _data/sidebars/
- mv README.adoc index.adoc
- sed -i 's/\/jekyll/\/'$REPO_NAME'/g' ./_config.yml
- sed -i 's/^.*searchyll.*//g' ./Gemfile
- sed -i 's/^.*searchyll.*//g' ./_config.yml;
- sed -i 's/search\:\s*true/search\:\ false/g' ./_config.yml
script:
- bundle exec rake deploy
