---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Contribute content
      url: /index.html
    - title: Style for NetApp docs
      url: /style.html
    - title: AsciiDoc reference
      url: /asciidoc_syntax.html
